Edit cd file

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -42,6 +42,18 @@ jobs:
         run: |
           docker run -d -p 4000:4000 --name nodejs-app ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app:latest
 
+      - name: Test application endpoint
+        id: test_endpoint
+        run: |
+          set -e
+          response=$(curl -s http://localhost:4000)
+          if [ "$response" == "AM ISRAEL HAI!" ]; then
+            echo "Test passed: Received expected response 'AM ISRAEL HAI!'"
+          else
+            echo "Test failed: Received unexpected response '$response'"
+            exit 1
+          fi
+
       - name: Alert deployment success
         if: success()
         run: echo "Deployment successful!"
