Edit cd file test

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -48,8 +48,14 @@ jobs:
       - name: Test application endpoint
         id: test_endpoint
         run: |
-          docker ps -a
-          curl -sk http://localhost:4000
+          set -e
+          response=$(curl -s http://localhost:4000)
+          if [ "$response" == "AM ISRAEL HAI!" ]; then
+            echo "Test passed: Received expected response 'AM ISRAEL HAI!'"
+          else
+            echo "Test failed: Received unexpected response '$response'"
+            exit 1
+          fi
 
       - name: Alert deployment success
         if: success()
